### ISSUE TITLE
Does not work with Python 3

### ISSUE THREAD

**Issue by spkane** [tremby/py-lyrics#4]
I've created a pull request that updates the script for Python 3. It might need some tweaks to make it work with both Python 2.7 and Python 3.

https://github.com/tremby/py-lyrics/pull/3

**Comment by tremby** [comment]
I've made said tweaks. Thanks.

**Comment by tremby** [comment]
Didn't know anybody but me used this!

**Comment by spkane** [comment]
It is actually be used in this project over here:
https://github.com/ronilaukkarinen/pianobar-osx

That is why I stumbled on this issue.

**Comment by ronilaukkarinen** [comment]
py-lyrics is brilliant, thanks for the work! 👍
